/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.cmdlineparser.node;

import java.util.*;
import fr.umlv.ir2.compil.cmdlineparser.analysis.*;

public final class AHtmlOptionsEnd extends POptionsEnd
{
    private TOptHtml _optHtml_;
    private TQuote _right_;
    private POptionsStart _optionsStart_;

    public AHtmlOptionsEnd()
    {
    }

    public AHtmlOptionsEnd(
        TOptHtml _optHtml_,
        TQuote _right_,
        POptionsStart _optionsStart_)
    {
        setOptHtml(_optHtml_);

        setRight(_right_);

        setOptionsStart(_optionsStart_);

    }
    public Object clone()
    {
        return new AHtmlOptionsEnd(
            (TOptHtml) cloneNode(_optHtml_),
            (TQuote) cloneNode(_right_),
            (POptionsStart) cloneNode(_optionsStart_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHtmlOptionsEnd(this);
    }

    public TOptHtml getOptHtml()
    {
        return _optHtml_;
    }

    public void setOptHtml(TOptHtml node)
    {
        if(_optHtml_ != null)
        {
            _optHtml_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _optHtml_ = node;
    }

    public TQuote getRight()
    {
        return _right_;
    }

    public void setRight(TQuote node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public POptionsStart getOptionsStart()
    {
        return _optionsStart_;
    }

    public void setOptionsStart(POptionsStart node)
    {
        if(_optionsStart_ != null)
        {
            _optionsStart_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _optionsStart_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_optHtml_)
            + toString(_right_)
            + toString(_optionsStart_);
    }

    void removeChild(Node child)
    {
        if(_optHtml_ == child)
        {
            _optHtml_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

        if(_optionsStart_ == child)
        {
            _optionsStart_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_optHtml_ == oldChild)
        {
            setOptHtml((TOptHtml) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((TQuote) newChild);
            return;
        }

        if(_optionsStart_ == oldChild)
        {
            setOptionsStart((POptionsStart) newChild);
            return;
        }

    }
}
