/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.cmdlineparser.node;

import fr.umlv.ir2.compil.cmdlineparser.analysis.*;

public final class X2PId extends XPId
{
    private PId _pId_;

    public X2PId()
    {
    }

    public X2PId(
        PId _pId_)
    {
        setPId(_pId_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PId getPId()
    {
        return _pId_;
    }

    public void setPId(PId node)
    {
        if(_pId_ != null)
        {
            _pId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pId_ = node;
    }

    void removeChild(Node child)
    {
        if(_pId_ == child)
        {
            _pId_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pId_);
    }
}
