/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.cmdlineparser.lexer;

import java.io.*;
import java.util.*;
import fr.umlv.ir2.compil.cmdlineparser.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;

        if(gotoTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Lexer.class.getResourceAsStream("lexer.dat")));

                // read gotoTable
                int length = s.readInt();
                gotoTable = new int[length][][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][][];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        length = s.readInt();
                        gotoTable[i][j] = new int[length][3];
                        for(int k = 0; k < gotoTable[i][j].length; k++)
                        {
                            for(int l = 0; l < 3; l++)
                            {
                                gotoTable[i][j][k][l] = s.readInt();
                            }
                        }
                    }
                }

                // read accept
                length = s.readInt();
                accept = new int[length][];
                for(int i = 0; i < accept.length; i++)
                {
                    length = s.readInt();
                    accept[i] = new int[length];
                    for(int j = 0; j < accept[i].length; j++)
                    {
                        accept[i][j] = s.readInt();
                    }
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
            }
        }
    }

    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(int line, int pos) { return new TQuote(line, pos); }
    Token new1(String text, int line, int pos) { return new TOptVerbose(text, line, pos); }
    Token new2(String text, int line, int pos) { return new TOptHelp(text, line, pos); }
    Token new3(String text, int line, int pos) { return new TOptLex(text, line, pos); }
    Token new4(String text, int line, int pos) { return new TOptI(text, line, pos); }
    Token new5(String text, int line, int pos) { return new TOptHtml(text, line, pos); }
    Token new6(String text, int line, int pos) { return new TOptHtmlFile(text, line, pos); }
    Token new7(String text, int line, int pos) { return new TOptX86(text, line, pos); }
    Token new8(String text, int line, int pos) { return new TOptObj(text, line, pos); }
    Token new9(String text, int line, int pos) { return new TOptVm(text, line, pos); }
    Token new10(String text, int line, int pos) { return new TId(text, line, pos); }
    Token new11(String text, int line, int pos) { return new TBlank(text, line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{0, 8, 1}, {9, 9, 2}, {10, 10, 3}, {11, 12, 1}, {13, 13, 4}, {14, 31, 1}, {32, 32, 5}, {33, 33, 1}, {34, 34, 6}, {35, 44, 1}, {45, 45, 7}, {46, 46, 1}, {47, 47, 8}, {48, 65535, 1}, },
            {{0, 9, 1}, {11, 12, 1}, {14, 33, 1}, {35, 65535, 1}, },
            {{0, 33, -2}, {35, 65535, 1}, },
            {{9, 9, 9}, {10, 10, 3}, {13, 13, 4}, {32, 32, 10}, },
            {{9, 9, 9}, {10, 10, 11}, {13, 32, -5}, },
            {{0, 65535, -4}, },
            {},
            {{0, 33, -3}, {35, 44, 1}, {45, 45, 12}, {46, 99, 1}, {100, 100, 13}, {101, 103, 1}, {104, 104, 14}, {105, 105, 15}, {106, 107, 1}, {108, 108, 16}, {109, 110, 1}, {111, 111, 17}, {112, 117, 1}, {118, 118, 18}, {119, 119, 1}, {120, 120, 19}, {121, 65535, 1}, },
            {{0, 33, -3}, {35, 99, 1}, {100, 65535, -9}, },
            {{9, 32, -5}, },
            {{9, 32, -5}, },
            {{9, 32, -5}, },
            {{0, 65535, -10}, },
            {{0, 65535, -3}, },
            {{0, 33, -3}, {35, 100, 1}, {101, 101, 20}, {102, 115, 1}, {116, 116, 21}, {117, 65535, 1}, },
            {{0, 33, -3}, {35, 109, 1}, {110, 110, 22}, {111, 65535, 1}, },
            {{0, 100, -16}, {101, 101, 23}, {102, 65535, 1}, },
            {{0, 65535, -3}, },
            {{0, 100, -16}, {101, 101, 24}, {102, 108, 1}, {109, 109, 25}, {110, 65535, 1}, },
            {{0, 33, -3}, {35, 55, 1}, {56, 56, 26}, {57, 65535, 1}, },
            {{0, 33, -3}, {35, 107, 1}, {108, 108, 27}, {109, 65535, 1}, },
            {{0, 33, -3}, {35, 108, 1}, {109, 109, 28}, {110, 65535, 1}, },
            {{0, 33, -3}, {35, 101, 1}, {102, 102, 29}, {103, 65535, 1}, },
            {{0, 33, -3}, {35, 119, 1}, {120, 120, 30}, {121, 65535, 1}, },
            {{0, 33, -3}, {35, 113, 1}, {114, 114, 31}, {115, 65535, 1}, },
            {{0, 65535, -3}, },
            {{0, 33, -3}, {35, 53, 1}, {54, 54, 32}, {55, 65535, 1}, },
            {{0, 33, -3}, {35, 111, 1}, {112, 112, 33}, {113, 65535, 1}, },
            {{0, 107, -22}, {108, 108, 34}, {109, 65535, 1}, },
            {{0, 33, -3}, {35, 110, 1}, {111, 111, 35}, {112, 65535, 1}, },
            {{0, 65535, -3}, },
            {{0, 33, -3}, {35, 97, 1}, {98, 98, 36}, {99, 65535, 1}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 110, -31}, {111, 111, 37}, {112, 65535, 1}, },
            {{0, 33, -3}, {35, 114, 1}, {115, 115, 38}, {116, 65535, 1}, },
            {{0, 100, -16}, {101, 101, 39}, {102, 65535, 1}, },
            {{0, 65535, -3}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {10, 10, 10, 11, 11, 10, 0, 10, 10, 11, 11, 11, 10, 6, 2, 4, 3, 8, 1, 10, 10, 10, 10, 10, 10, 9, 10, 10, 10, 10, 3, 10, 7, 2, 5, 4, 10, 10, 10, 1, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }
}
