/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import java.util.*;
import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class ABoolConstants extends PConstants
{
    private TBool _bool_;

    public ABoolConstants()
    {
    }

    public ABoolConstants(
        TBool _bool_)
    {
        setBool(_bool_);

    }
    public Object clone()
    {
        return new ABoolConstants(
            (TBool) cloneNode(_bool_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolConstants(this);
    }

    public TBool getBool()
    {
        return _bool_;
    }

    public void setBool(TBool node)
    {
        if(_bool_ != null)
        {
            _bool_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _bool_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_bool_);
    }

    void removeChild(Node child)
    {
        if(_bool_ == child)
        {
            _bool_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_bool_ == oldChild)
        {
            setBool((TBool) newChild);
            return;
        }

    }
}
