/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import java.util.*;
import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class ADivExprProduct extends PExprProduct
{
    private PExprProduct _exprProduct_;
    private TDiv _div_;
    private PExprUnary _exprUnary_;

    public ADivExprProduct()
    {
    }

    public ADivExprProduct(
        PExprProduct _exprProduct_,
        TDiv _div_,
        PExprUnary _exprUnary_)
    {
        setExprProduct(_exprProduct_);

        setDiv(_div_);

        setExprUnary(_exprUnary_);

    }
    public Object clone()
    {
        return new ADivExprProduct(
            (PExprProduct) cloneNode(_exprProduct_),
            (TDiv) cloneNode(_div_),
            (PExprUnary) cloneNode(_exprUnary_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivExprProduct(this);
    }

    public PExprProduct getExprProduct()
    {
        return _exprProduct_;
    }

    public void setExprProduct(PExprProduct node)
    {
        if(_exprProduct_ != null)
        {
            _exprProduct_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprProduct_ = node;
    }

    public TDiv getDiv()
    {
        return _div_;
    }

    public void setDiv(TDiv node)
    {
        if(_div_ != null)
        {
            _div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _div_ = node;
    }

    public PExprUnary getExprUnary()
    {
        return _exprUnary_;
    }

    public void setExprUnary(PExprUnary node)
    {
        if(_exprUnary_ != null)
        {
            _exprUnary_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprUnary_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprProduct_)
            + toString(_div_)
            + toString(_exprUnary_);
    }

    void removeChild(Node child)
    {
        if(_exprProduct_ == child)
        {
            _exprProduct_ = null;
            return;
        }

        if(_div_ == child)
        {
            _div_ = null;
            return;
        }

        if(_exprUnary_ == child)
        {
            _exprUnary_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprProduct_ == oldChild)
        {
            setExprProduct((PExprProduct) newChild);
            return;
        }

        if(_div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(_exprUnary_ == oldChild)
        {
            setExprUnary((PExprUnary) newChild);
            return;
        }

    }
}
