/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import java.util.*;
import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class AEqualExprComp extends PExprComp
{
    private PExprComp _exprComp_;
    private TEqual _equal_;
    private PExprSum _exprSum_;

    public AEqualExprComp()
    {
    }

    public AEqualExprComp(
        PExprComp _exprComp_,
        TEqual _equal_,
        PExprSum _exprSum_)
    {
        setExprComp(_exprComp_);

        setEqual(_equal_);

        setExprSum(_exprSum_);

    }
    public Object clone()
    {
        return new AEqualExprComp(
            (PExprComp) cloneNode(_exprComp_),
            (TEqual) cloneNode(_equal_),
            (PExprSum) cloneNode(_exprSum_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqualExprComp(this);
    }

    public PExprComp getExprComp()
    {
        return _exprComp_;
    }

    public void setExprComp(PExprComp node)
    {
        if(_exprComp_ != null)
        {
            _exprComp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprComp_ = node;
    }

    public TEqual getEqual()
    {
        return _equal_;
    }

    public void setEqual(TEqual node)
    {
        if(_equal_ != null)
        {
            _equal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _equal_ = node;
    }

    public PExprSum getExprSum()
    {
        return _exprSum_;
    }

    public void setExprSum(PExprSum node)
    {
        if(_exprSum_ != null)
        {
            _exprSum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprSum_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprComp_)
            + toString(_equal_)
            + toString(_exprSum_);
    }

    void removeChild(Node child)
    {
        if(_exprComp_ == child)
        {
            _exprComp_ = null;
            return;
        }

        if(_equal_ == child)
        {
            _equal_ = null;
            return;
        }

        if(_exprSum_ == child)
        {
            _exprSum_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprComp_ == oldChild)
        {
            setExprComp((PExprComp) newChild);
            return;
        }

        if(_equal_ == oldChild)
        {
            setEqual((TEqual) newChild);
            return;
        }

        if(_exprSum_ == oldChild)
        {
            setExprSum((PExprSum) newChild);
            return;
        }

    }
}
