/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import java.util.*;
import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class ALogicExpression extends PExpression
{
    private PExprLogic _exprLogic_;

    public ALogicExpression()
    {
    }

    public ALogicExpression(
        PExprLogic _exprLogic_)
    {
        setExprLogic(_exprLogic_);

    }
    public Object clone()
    {
        return new ALogicExpression(
            (PExprLogic) cloneNode(_exprLogic_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogicExpression(this);
    }

    public PExprLogic getExprLogic()
    {
        return _exprLogic_;
    }

    public void setExprLogic(PExprLogic node)
    {
        if(_exprLogic_ != null)
        {
            _exprLogic_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprLogic_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprLogic_);
    }

    void removeChild(Node child)
    {
        if(_exprLogic_ == child)
        {
            _exprLogic_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprLogic_ == oldChild)
        {
            setExprLogic((PExprLogic) newChild);
            return;
        }

    }
}
