/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import java.util.*;
import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class ALteqExprComp extends PExprComp
{
    private PExprComp _exprComp_;
    private TLteq _lteq_;
    private PExprSum _exprSum_;

    public ALteqExprComp()
    {
    }

    public ALteqExprComp(
        PExprComp _exprComp_,
        TLteq _lteq_,
        PExprSum _exprSum_)
    {
        setExprComp(_exprComp_);

        setLteq(_lteq_);

        setExprSum(_exprSum_);

    }
    public Object clone()
    {
        return new ALteqExprComp(
            (PExprComp) cloneNode(_exprComp_),
            (TLteq) cloneNode(_lteq_),
            (PExprSum) cloneNode(_exprSum_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALteqExprComp(this);
    }

    public PExprComp getExprComp()
    {
        return _exprComp_;
    }

    public void setExprComp(PExprComp node)
    {
        if(_exprComp_ != null)
        {
            _exprComp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprComp_ = node;
    }

    public TLteq getLteq()
    {
        return _lteq_;
    }

    public void setLteq(TLteq node)
    {
        if(_lteq_ != null)
        {
            _lteq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lteq_ = node;
    }

    public PExprSum getExprSum()
    {
        return _exprSum_;
    }

    public void setExprSum(PExprSum node)
    {
        if(_exprSum_ != null)
        {
            _exprSum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprSum_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprComp_)
            + toString(_lteq_)
            + toString(_exprSum_);
    }

    void removeChild(Node child)
    {
        if(_exprComp_ == child)
        {
            _exprComp_ = null;
            return;
        }

        if(_lteq_ == child)
        {
            _lteq_ = null;
            return;
        }

        if(_exprSum_ == child)
        {
            _exprSum_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprComp_ == oldChild)
        {
            setExprComp((PExprComp) newChild);
            return;
        }

        if(_lteq_ == oldChild)
        {
            setLteq((TLteq) newChild);
            return;
        }

        if(_exprSum_ == oldChild)
        {
            setExprSum((PExprSum) newChild);
            return;
        }

    }
}
