/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import java.util.*;
import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class APlusExprSum extends PExprSum
{
    private PExprSum _exprSum_;
    private TPlus _plus_;
    private PExprProduct _exprProduct_;

    public APlusExprSum()
    {
    }

    public APlusExprSum(
        PExprSum _exprSum_,
        TPlus _plus_,
        PExprProduct _exprProduct_)
    {
        setExprSum(_exprSum_);

        setPlus(_plus_);

        setExprProduct(_exprProduct_);

    }
    public Object clone()
    {
        return new APlusExprSum(
            (PExprSum) cloneNode(_exprSum_),
            (TPlus) cloneNode(_plus_),
            (PExprProduct) cloneNode(_exprProduct_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusExprSum(this);
    }

    public PExprSum getExprSum()
    {
        return _exprSum_;
    }

    public void setExprSum(PExprSum node)
    {
        if(_exprSum_ != null)
        {
            _exprSum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprSum_ = node;
    }

    public TPlus getPlus()
    {
        return _plus_;
    }

    public void setPlus(TPlus node)
    {
        if(_plus_ != null)
        {
            _plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _plus_ = node;
    }

    public PExprProduct getExprProduct()
    {
        return _exprProduct_;
    }

    public void setExprProduct(PExprProduct node)
    {
        if(_exprProduct_ != null)
        {
            _exprProduct_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprProduct_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprSum_)
            + toString(_plus_)
            + toString(_exprProduct_);
    }

    void removeChild(Node child)
    {
        if(_exprSum_ == child)
        {
            _exprSum_ = null;
            return;
        }

        if(_plus_ == child)
        {
            _plus_ = null;
            return;
        }

        if(_exprProduct_ == child)
        {
            _exprProduct_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprSum_ == oldChild)
        {
            setExprSum((PExprSum) newChild);
            return;
        }

        if(_plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(_exprProduct_ == oldChild)
        {
            setExprProduct((PExprProduct) newChild);
            return;
        }

    }
}
