/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import java.util.*;
import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class AXorExprLogic extends PExprLogic
{
    private PExprLogic _exprLogic_;
    private TXor _xor_;
    private PExprComp _exprComp_;

    public AXorExprLogic()
    {
    }

    public AXorExprLogic(
        PExprLogic _exprLogic_,
        TXor _xor_,
        PExprComp _exprComp_)
    {
        setExprLogic(_exprLogic_);

        setXor(_xor_);

        setExprComp(_exprComp_);

    }
    public Object clone()
    {
        return new AXorExprLogic(
            (PExprLogic) cloneNode(_exprLogic_),
            (TXor) cloneNode(_xor_),
            (PExprComp) cloneNode(_exprComp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAXorExprLogic(this);
    }

    public PExprLogic getExprLogic()
    {
        return _exprLogic_;
    }

    public void setExprLogic(PExprLogic node)
    {
        if(_exprLogic_ != null)
        {
            _exprLogic_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprLogic_ = node;
    }

    public TXor getXor()
    {
        return _xor_;
    }

    public void setXor(TXor node)
    {
        if(_xor_ != null)
        {
            _xor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xor_ = node;
    }

    public PExprComp getExprComp()
    {
        return _exprComp_;
    }

    public void setExprComp(PExprComp node)
    {
        if(_exprComp_ != null)
        {
            _exprComp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprComp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprLogic_)
            + toString(_xor_)
            + toString(_exprComp_);
    }

    void removeChild(Node child)
    {
        if(_exprLogic_ == child)
        {
            _exprLogic_ = null;
            return;
        }

        if(_xor_ == child)
        {
            _xor_ = null;
            return;
        }

        if(_exprComp_ == child)
        {
            _exprComp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprLogic_ == oldChild)
        {
            setExprLogic((PExprLogic) newChild);
            return;
        }

        if(_xor_ == oldChild)
        {
            setXor((TXor) newChild);
            return;
        }

        if(_exprComp_ == oldChild)
        {
            setExprComp((PExprComp) newChild);
            return;
        }

    }
}
