/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class TMcBool extends Token
{
    public TMcBool()
    {
        super.setText("bool");
    }

    public TMcBool(int line, int pos)
    {
        super.setText("bool");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMcBool(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMcBool(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMcBool text.");
    }
}
