/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class TMcInt extends Token
{
    public TMcInt()
    {
        super.setText("int");
    }

    public TMcInt(int line, int pos)
    {
        super.setText("int");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMcInt(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMcInt(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMcInt text.");
    }
}
