/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class TMcIn extends Token
{
    public TMcIn()
    {
        super.setText("in");
    }

    public TMcIn(int line, int pos)
    {
        super.setText("in");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMcIn(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMcIn(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMcIn text.");
    }
}
