/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class TMcIf extends Token
{
    public TMcIf()
    {
        super.setText("if");
    }

    public TMcIf(int line, int pos)
    {
        super.setText("if");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMcIf(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMcIf(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMcIf text.");
    }
}
