/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class TMcNot extends Token
{
    public TMcNot()
    {
        super.setText("not");
    }

    public TMcNot(int line, int pos)
    {
        super.setText("not");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMcNot(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMcNot(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMcNot text.");
    }
}
