/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class TXor extends Token
{
    public TXor()
    {
        super.setText("^^");
    }

    public TXor(int line, int pos)
    {
        super.setText("^^");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TXor(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXor(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TXor text.");
    }
}
