/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class X2PDeclarations extends XPDeclarations
{
    private PDeclarations _pDeclarations_;

    public X2PDeclarations()
    {
    }

    public X2PDeclarations(
        PDeclarations _pDeclarations_)
    {
        setPDeclarations(_pDeclarations_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PDeclarations getPDeclarations()
    {
        return _pDeclarations_;
    }

    public void setPDeclarations(PDeclarations node)
    {
        if(_pDeclarations_ != null)
        {
            _pDeclarations_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pDeclarations_ = node;
    }

    void removeChild(Node child)
    {
        if(_pDeclarations_ == child)
        {
            _pDeclarations_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pDeclarations_);
    }
}
