/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.cmdlineparser.parser;

import fr.umlv.ir2.compil.cmdlineparser.node.*;
import fr.umlv.ir2.compil.cmdlineparser.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTQuote(TQuote node)
    {
        index = 0;
    }

    public void caseTOptVerbose(TOptVerbose node)
    {
        index = 1;
    }

    public void caseTOptHelp(TOptHelp node)
    {
        index = 2;
    }

    public void caseTOptLex(TOptLex node)
    {
        index = 3;
    }

    public void caseTOptI(TOptI node)
    {
        index = 4;
    }

    public void caseTOptHtml(TOptHtml node)
    {
        index = 5;
    }

    public void caseTOptHtmlFile(TOptHtmlFile node)
    {
        index = 6;
    }

    public void caseTOptX86(TOptX86 node)
    {
        index = 7;
    }

    public void caseTOptObj(TOptObj node)
    {
        index = 8;
    }

    public void caseTOptVm(TOptVm node)
    {
        index = 9;
    }

    public void caseTId(TId node)
    {
        index = 10;
    }

    public void caseEOF(EOF node)
    {
        index = 11;
    }
}
