/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.lexer;

import java.io.*;
import java.util.*;
import fr.umlv.ir2.compil.languageparser.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;

        if(gotoTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Lexer.class.getResourceAsStream("lexer.dat")));

                // read gotoTable
                int length = s.readInt();
                gotoTable = new int[length][][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][][];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        length = s.readInt();
                        gotoTable[i][j] = new int[length][3];
                        for(int k = 0; k < gotoTable[i][j].length; k++)
                        {
                            for(int l = 0; l < 3; l++)
                            {
                                gotoTable[i][j][k][l] = s.readInt();
                            }
                        }
                    }
                }

                // read accept
                length = s.readInt();
                accept = new int[length][];
                for(int i = 0; i < accept.length; i++)
                {
                    length = s.readInt();
                    accept[i] = new int[length];
                    for(int j = 0; j < accept[i].length; j++)
                    {
                        accept[i][j] = s.readInt();
                    }
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
            }
        }
    }

    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = new14(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = new15(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = new16(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = new17(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = new18(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = new27(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = new30(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            Token token = new38(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(int line, int pos) { return new TMcVar(line, pos); }
    Token new1(int line, int pos) { return new TMcFunction(line, pos); }
    Token new2(int line, int pos) { return new TMcPrint(line, pos); }
    Token new3(int line, int pos) { return new TMcFor(line, pos); }
    Token new4(int line, int pos) { return new TMcTo(line, pos); }
    Token new5(int line, int pos) { return new TMcInt(line, pos); }
    Token new6(int line, int pos) { return new TMcFloat(line, pos); }
    Token new7(int line, int pos) { return new TMcBool(line, pos); }
    Token new8(int line, int pos) { return new TMcIf(line, pos); }
    Token new9(int line, int pos) { return new TMcThen(line, pos); }
    Token new10(int line, int pos) { return new TMcElse(line, pos); }
    Token new11(int line, int pos) { return new TMcLet(line, pos); }
    Token new12(int line, int pos) { return new TMcIn(line, pos); }
    Token new13(int line, int pos) { return new TMcNot(line, pos); }
    Token new14(String text, int line, int pos) { return new TType(text, line, pos); }
    Token new15(String text, int line, int pos) { return new TInt(text, line, pos); }
    Token new16(String text, int line, int pos) { return new TFloat(text, line, pos); }
    Token new17(String text, int line, int pos) { return new TBool(text, line, pos); }
    Token new18(String text, int line, int pos) { return new TId(text, line, pos); }
    Token new19(int line, int pos) { return new TEqual(line, pos); }
    Token new20(int line, int pos) { return new TLPar(line, pos); }
    Token new21(int line, int pos) { return new TRPar(line, pos); }
    Token new22(int line, int pos) { return new TLBracket(line, pos); }
    Token new23(int line, int pos) { return new TRBracket(line, pos); }
    Token new24(int line, int pos) { return new TPlus(line, pos); }
    Token new25(int line, int pos) { return new TMinus(line, pos); }
    Token new26(int line, int pos) { return new TSemicolon(line, pos); }
    Token new27(String text, int line, int pos) { return new TMult(text, line, pos); }
    Token new28(int line, int pos) { return new TDiv(line, pos); }
    Token new29(int line, int pos) { return new TMod(line, pos); }
    Token new30(String text, int line, int pos) { return new TComma(text, line, pos); }
    Token new31(int line, int pos) { return new TLt(line, pos); }
    Token new32(int line, int pos) { return new TLteq(line, pos); }
    Token new33(int line, int pos) { return new TGt(line, pos); }
    Token new34(int line, int pos) { return new TGteq(line, pos); }
    Token new35(int line, int pos) { return new TAnd(line, pos); }
    Token new36(int line, int pos) { return new TOr(line, pos); }
    Token new37(int line, int pos) { return new TXor(line, pos); }
    Token new38(String text, int line, int pos) { return new TTexte(text, line, pos); }
    Token new39(String text, int line, int pos) { return new TBlank(text, line, pos); }
    Token new40(String text, int line, int pos) { return new TComment(text, line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {34, 34, 5}, {37, 37, 6}, {38, 38, 7}, {40, 40, 8}, {41, 41, 9}, {42, 42, 10}, {43, 43, 11}, {44, 44, 12}, {45, 45, 13}, {46, 46, 14}, {47, 47, 15}, {48, 57, 16}, {58, 58, 17}, {59, 59, 18}, {60, 60, 19}, {61, 61, 20}, {62, 62, 21}, {65, 90, 22}, {91, 91, 23}, {93, 93, 24}, {94, 94, 25}, {95, 95, 22}, {97, 97, 22}, {98, 98, 26}, {99, 100, 22}, {101, 101, 27}, {102, 102, 28}, {103, 104, 22}, {105, 105, 29}, {106, 107, 22}, {108, 108, 30}, {109, 109, 22}, {110, 110, 31}, {111, 111, 22}, {112, 112, 32}, {113, 115, 22}, {116, 116, 33}, {117, 117, 22}, {118, 118, 34}, {119, 122, 22}, {124, 124, 35}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 36}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {{0, 9, 37}, {11, 12, 37}, {14, 33, 37}, {35, 65535, 37}, },
            {},
            {{38, 38, 38}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 39}, },
            {{42, 42, 40}, {47, 47, 41}, },
            {{46, 46, 42}, {48, 57, 16}, {69, 69, 43}, {101, 101, 44}, },
            {{98, 98, 45}, {102, 102, 46}, {105, 105, 47}, },
            {},
            {{61, 61, 48}, },
            {},
            {{61, 61, 49}, },
            {{48, 57, 50}, {65, 90, 51}, {95, 95, 51}, {97, 122, 51}, },
            {},
            {},
            {{94, 94, 52}, },
            {{48, 95, -24}, {97, 110, 51}, {111, 111, 53}, {112, 122, 51}, },
            {{48, 95, -24}, {97, 107, 51}, {108, 108, 54}, {109, 122, 51}, },
            {{48, 95, -24}, {97, 97, 55}, {98, 107, 51}, {108, 108, 56}, {109, 110, 51}, {111, 111, 57}, {112, 116, 51}, {117, 117, 58}, {118, 122, 51}, },
            {{48, 95, -24}, {97, 101, 51}, {102, 102, 59}, {103, 109, 51}, {110, 110, 60}, {111, 122, 51}, },
            {{48, 95, -24}, {97, 100, 51}, {101, 101, 61}, {102, 122, 51}, },
            {{48, 110, -28}, {111, 111, 62}, {112, 122, 51}, },
            {{48, 95, -24}, {97, 113, 51}, {114, 114, 63}, {115, 122, 51}, },
            {{48, 95, -24}, {97, 103, 51}, {104, 104, 64}, {105, 110, 51}, {111, 111, 65}, {112, 113, 51}, {114, 114, 66}, {115, 122, 51}, },
            {{48, 95, -24}, {97, 97, 67}, {98, 122, 51}, },
            {{124, 124, 68}, },
            {{9, 32, -2}, },
            {{0, 33, -7}, {34, 34, 69}, {35, 65535, 37}, },
            {},
            {{48, 57, 39}, {69, 69, 70}, {70, 70, 71}, {76, 76, 72}, {101, 101, 73}, {102, 102, 74}, {108, 108, 75}, },
            {{0, 41, 76}, {42, 42, 77}, {43, 65535, 76}, },
            {{0, 9, 78}, {10, 10, 79}, {11, 12, 78}, {13, 13, 80}, {14, 65535, 78}, },
            {{48, 108, -41}, },
            {{43, 43, 81}, {45, 45, 82}, {48, 57, 83}, },
            {{43, 57, -45}, },
            {{111, 111, 84}, },
            {{108, 108, 85}, },
            {{110, 110, 86}, },
            {},
            {},
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {},
            {{48, 110, -28}, {111, 111, 87}, {112, 122, 51}, },
            {{48, 95, -24}, {97, 114, 51}, {115, 115, 88}, {116, 122, 51}, },
            {{48, 107, -29}, {108, 108, 89}, {109, 122, 51}, },
            {{48, 110, -28}, {111, 111, 90}, {112, 122, 51}, },
            {{48, 113, -34}, {114, 114, 91}, {115, 122, 51}, },
            {{48, 95, -24}, {97, 109, 51}, {110, 110, 92}, {111, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 115, 51}, {116, 116, 93}, {117, 122, 51}, },
            {{48, 115, -62}, {116, 116, 94}, {117, 122, 51}, },
            {{48, 115, -62}, {116, 116, 95}, {117, 122, 51}, },
            {{48, 95, -24}, {97, 104, 51}, {105, 105, 96}, {106, 122, 51}, },
            {{48, 100, -32}, {101, 101, 97}, {102, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 116, 51}, {117, 117, 98}, {118, 122, 51}, },
            {{48, 113, -34}, {114, 114, 99}, {115, 122, 51}, },
            {},
            {},
            {{43, 43, 100}, {45, 45, 101}, {48, 57, 102}, },
            {},
            {},
            {{43, 57, -72}, },
            {},
            {},
            {{0, 65535, -42}, },
            {{0, 41, 103}, {42, 42, 77}, {43, 46, 103}, {47, 47, 104}, {48, 65535, 103}, },
            {{0, 65535, -43}, },
            {},
            {{10, 10, 105}, },
            {{48, 57, 83}, },
            {{48, 57, 83}, },
            {{48, 57, 83}, {70, 70, 106}, {76, 76, 107}, {102, 102, 108}, {108, 108, 109}, },
            {{111, 111, 110}, },
            {{111, 111, 111}, },
            {{116, 116, 112}, },
            {{48, 107, -29}, {108, 108, 113}, {109, 122, 51}, },
            {{48, 100, -32}, {101, 101, 114}, {102, 122, 51}, },
            {{48, 114, -56}, {115, 115, 115}, {116, 122, 51}, },
            {{48, 95, -24}, {97, 97, 116}, {98, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 98, 51}, {99, 99, 117}, {100, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 109, -60}, {110, 110, 118}, {111, 122, 51}, },
            {{48, 109, -60}, {110, 110, 119}, {111, 122, 51}, },
            {{48, 100, -32}, {101, 101, 120}, {102, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 57, 102}, },
            {{48, 57, 102}, },
            {{48, 57, 102}, {70, 76, -41}, {102, 108, -41}, },
            {{0, 65535, -42}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{108, 108, 121}, },
            {{97, 97, 122}, },
            {},
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 100, -32}, {101, 101, 123}, {102, 122, 51}, },
            {{48, 115, -62}, {116, 116, 124}, {117, 122, 51}, },
            {{48, 115, -62}, {116, 116, 125}, {117, 122, 51}, },
            {{48, 115, -62}, {116, 116, 126}, {117, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {},
            {{116, 116, 127}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 104, -65}, {105, 105, 128}, {106, 122, 51}, },
            {{48, 122, -24}, },
            {},
            {{48, 110, -28}, {111, 111, 129}, {112, 122, 51}, },
            {{48, 109, -60}, {110, 110, 130}, {111, 122, 51}, },
            {{48, 122, -24}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 39, 39, 39, 39, -1, 29, -1, 20, 21, 27, 24, 30, 25, -1, 28, 15, -1, 26, 31, 19, 33, 18, 22, 23, -1, 18, 18, 18, 18, 18, 18, 18, 18, 18, -1, 39, -1, 35, 16, -1, -1, 16, -1, -1, -1, -1, -1, 32, 34, 18, 18, 37, 18, 18, 18, 18, 18, 18, 8, 12, 18, 18, 18, 18, 4, 18, 18, 36, 38, -1, 16, 16, -1, 16, 16, -1, -1, -1, 40, 40, -1, -1, 16, -1, -1, -1, 18, 18, 18, 18, 3, 18, 5, 11, 13, 18, 18, 18, 0, -1, -1, 16, -1, 40, 40, 16, 16, 16, 16, -1, -1, 14, 7, 10, 18, 18, 18, 18, 9, 17, 14, -1, 17, 6, 18, 2, 14, 18, 18, 1, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }
}
