/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import java.util.*;
import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class AConstantsExprSimple extends PExprSimple
{
    private PConstants _constants_;

    public AConstantsExprSimple()
    {
    }

    public AConstantsExprSimple(
        PConstants _constants_)
    {
        setConstants(_constants_);

    }
    public Object clone()
    {
        return new AConstantsExprSimple(
            (PConstants) cloneNode(_constants_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConstantsExprSimple(this);
    }

    public PConstants getConstants()
    {
        return _constants_;
    }

    public void setConstants(PConstants node)
    {
        if(_constants_ != null)
        {
            _constants_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _constants_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_constants_);
    }

    void removeChild(Node child)
    {
        if(_constants_ == child)
        {
            _constants_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_constants_ == oldChild)
        {
            setConstants((PConstants) newChild);
            return;
        }

    }
}
