/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import java.util.*;
import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class AEmptyExprLogic extends PExprLogic
{
    private PExprComp _exprComp_;

    public AEmptyExprLogic()
    {
    }

    public AEmptyExprLogic(
        PExprComp _exprComp_)
    {
        setExprComp(_exprComp_);

    }
    public Object clone()
    {
        return new AEmptyExprLogic(
            (PExprComp) cloneNode(_exprComp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyExprLogic(this);
    }

    public PExprComp getExprComp()
    {
        return _exprComp_;
    }

    public void setExprComp(PExprComp node)
    {
        if(_exprComp_ != null)
        {
            _exprComp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprComp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprComp_);
    }

    void removeChild(Node child)
    {
        if(_exprComp_ == child)
        {
            _exprComp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprComp_ == oldChild)
        {
            setExprComp((PExprComp) newChild);
            return;
        }

    }
}
