/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import java.util.*;
import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class AEmptyExprProduct extends PExprProduct
{
    private PExprUnary _exprUnary_;

    public AEmptyExprProduct()
    {
    }

    public AEmptyExprProduct(
        PExprUnary _exprUnary_)
    {
        setExprUnary(_exprUnary_);

    }
    public Object clone()
    {
        return new AEmptyExprProduct(
            (PExprUnary) cloneNode(_exprUnary_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyExprProduct(this);
    }

    public PExprUnary getExprUnary()
    {
        return _exprUnary_;
    }

    public void setExprUnary(PExprUnary node)
    {
        if(_exprUnary_ != null)
        {
            _exprUnary_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprUnary_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprUnary_);
    }

    void removeChild(Node child)
    {
        if(_exprUnary_ == child)
        {
            _exprUnary_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprUnary_ == oldChild)
        {
            setExprUnary((PExprUnary) newChild);
            return;
        }

    }
}
