/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import java.util.*;
import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class AGtExprComp extends PExprComp
{
    private PExprComp _exprComp_;
    private TGt _gt_;
    private PExprSum _exprSum_;

    public AGtExprComp()
    {
    }

    public AGtExprComp(
        PExprComp _exprComp_,
        TGt _gt_,
        PExprSum _exprSum_)
    {
        setExprComp(_exprComp_);

        setGt(_gt_);

        setExprSum(_exprSum_);

    }
    public Object clone()
    {
        return new AGtExprComp(
            (PExprComp) cloneNode(_exprComp_),
            (TGt) cloneNode(_gt_),
            (PExprSum) cloneNode(_exprSum_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGtExprComp(this);
    }

    public PExprComp getExprComp()
    {
        return _exprComp_;
    }

    public void setExprComp(PExprComp node)
    {
        if(_exprComp_ != null)
        {
            _exprComp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprComp_ = node;
    }

    public TGt getGt()
    {
        return _gt_;
    }

    public void setGt(TGt node)
    {
        if(_gt_ != null)
        {
            _gt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _gt_ = node;
    }

    public PExprSum getExprSum()
    {
        return _exprSum_;
    }

    public void setExprSum(PExprSum node)
    {
        if(_exprSum_ != null)
        {
            _exprSum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprSum_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprComp_)
            + toString(_gt_)
            + toString(_exprSum_);
    }

    void removeChild(Node child)
    {
        if(_exprComp_ == child)
        {
            _exprComp_ = null;
            return;
        }

        if(_gt_ == child)
        {
            _gt_ = null;
            return;
        }

        if(_exprSum_ == child)
        {
            _exprSum_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprComp_ == oldChild)
        {
            setExprComp((PExprComp) newChild);
            return;
        }

        if(_gt_ == oldChild)
        {
            setGt((TGt) newChild);
            return;
        }

        if(_exprSum_ == oldChild)
        {
            setExprSum((PExprSum) newChild);
            return;
        }

    }
}
