/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import java.util.*;
import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class ALtExprComp extends PExprComp
{
    private PExprComp _exprComp_;
    private TLt _lt_;
    private PExprSum _exprSum_;

    public ALtExprComp()
    {
    }

    public ALtExprComp(
        PExprComp _exprComp_,
        TLt _lt_,
        PExprSum _exprSum_)
    {
        setExprComp(_exprComp_);

        setLt(_lt_);

        setExprSum(_exprSum_);

    }
    public Object clone()
    {
        return new ALtExprComp(
            (PExprComp) cloneNode(_exprComp_),
            (TLt) cloneNode(_lt_),
            (PExprSum) cloneNode(_exprSum_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALtExprComp(this);
    }

    public PExprComp getExprComp()
    {
        return _exprComp_;
    }

    public void setExprComp(PExprComp node)
    {
        if(_exprComp_ != null)
        {
            _exprComp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprComp_ = node;
    }

    public TLt getLt()
    {
        return _lt_;
    }

    public void setLt(TLt node)
    {
        if(_lt_ != null)
        {
            _lt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lt_ = node;
    }

    public PExprSum getExprSum()
    {
        return _exprSum_;
    }

    public void setExprSum(PExprSum node)
    {
        if(_exprSum_ != null)
        {
            _exprSum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprSum_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprComp_)
            + toString(_lt_)
            + toString(_exprSum_);
    }

    void removeChild(Node child)
    {
        if(_exprComp_ == child)
        {
            _exprComp_ = null;
            return;
        }

        if(_lt_ == child)
        {
            _lt_ = null;
            return;
        }

        if(_exprSum_ == child)
        {
            _exprSum_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprComp_ == oldChild)
        {
            setExprComp((PExprComp) newChild);
            return;
        }

        if(_lt_ == oldChild)
        {
            setLt((TLt) newChild);
            return;
        }

        if(_exprSum_ == oldChild)
        {
            setExprSum((PExprSum) newChild);
            return;
        }

    }
}
