/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import java.util.*;
import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class AMinusExprSum extends PExprSum
{
    private PExprSum _exprSum_;
    private TMinus _minus_;
    private PExprProduct _exprProduct_;

    public AMinusExprSum()
    {
    }

    public AMinusExprSum(
        PExprSum _exprSum_,
        TMinus _minus_,
        PExprProduct _exprProduct_)
    {
        setExprSum(_exprSum_);

        setMinus(_minus_);

        setExprProduct(_exprProduct_);

    }
    public Object clone()
    {
        return new AMinusExprSum(
            (PExprSum) cloneNode(_exprSum_),
            (TMinus) cloneNode(_minus_),
            (PExprProduct) cloneNode(_exprProduct_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinusExprSum(this);
    }

    public PExprSum getExprSum()
    {
        return _exprSum_;
    }

    public void setExprSum(PExprSum node)
    {
        if(_exprSum_ != null)
        {
            _exprSum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprSum_ = node;
    }

    public TMinus getMinus()
    {
        return _minus_;
    }

    public void setMinus(TMinus node)
    {
        if(_minus_ != null)
        {
            _minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _minus_ = node;
    }

    public PExprProduct getExprProduct()
    {
        return _exprProduct_;
    }

    public void setExprProduct(PExprProduct node)
    {
        if(_exprProduct_ != null)
        {
            _exprProduct_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprProduct_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprSum_)
            + toString(_minus_)
            + toString(_exprProduct_);
    }

    void removeChild(Node child)
    {
        if(_exprSum_ == child)
        {
            _exprSum_ = null;
            return;
        }

        if(_minus_ == child)
        {
            _minus_ = null;
            return;
        }

        if(_exprProduct_ == child)
        {
            _exprProduct_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprSum_ == oldChild)
        {
            setExprSum((PExprSum) newChild);
            return;
        }

        if(_minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(_exprProduct_ == oldChild)
        {
            setExprProduct((PExprProduct) newChild);
            return;
        }

    }
}
