/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import java.util.*;
import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class AMultExprProduct extends PExprProduct
{
    private PExprProduct _exprProduct_;
    private TMult _mult_;
    private PExprUnary _exprUnary_;

    public AMultExprProduct()
    {
    }

    public AMultExprProduct(
        PExprProduct _exprProduct_,
        TMult _mult_,
        PExprUnary _exprUnary_)
    {
        setExprProduct(_exprProduct_);

        setMult(_mult_);

        setExprUnary(_exprUnary_);

    }
    public Object clone()
    {
        return new AMultExprProduct(
            (PExprProduct) cloneNode(_exprProduct_),
            (TMult) cloneNode(_mult_),
            (PExprUnary) cloneNode(_exprUnary_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultExprProduct(this);
    }

    public PExprProduct getExprProduct()
    {
        return _exprProduct_;
    }

    public void setExprProduct(PExprProduct node)
    {
        if(_exprProduct_ != null)
        {
            _exprProduct_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprProduct_ = node;
    }

    public TMult getMult()
    {
        return _mult_;
    }

    public void setMult(TMult node)
    {
        if(_mult_ != null)
        {
            _mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _mult_ = node;
    }

    public PExprUnary getExprUnary()
    {
        return _exprUnary_;
    }

    public void setExprUnary(PExprUnary node)
    {
        if(_exprUnary_ != null)
        {
            _exprUnary_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exprUnary_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exprProduct_)
            + toString(_mult_)
            + toString(_exprUnary_);
    }

    void removeChild(Node child)
    {
        if(_exprProduct_ == child)
        {
            _exprProduct_ = null;
            return;
        }

        if(_mult_ == child)
        {
            _mult_ = null;
            return;
        }

        if(_exprUnary_ == child)
        {
            _exprUnary_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exprProduct_ == oldChild)
        {
            setExprProduct((PExprProduct) newChild);
            return;
        }

        if(_mult_ == oldChild)
        {
            setMult((TMult) newChild);
            return;
        }

        if(_exprUnary_ == oldChild)
        {
            setExprUnary((PExprUnary) newChild);
            return;
        }

    }
}
