/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import java.util.*;
import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class APlusUnaryOp extends PUnaryOp
{
    private TPlus _plus_;

    public APlusUnaryOp()
    {
    }

    public APlusUnaryOp(
        TPlus _plus_)
    {
        setPlus(_plus_);

    }
    public Object clone()
    {
        return new APlusUnaryOp(
            (TPlus) cloneNode(_plus_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusUnaryOp(this);
    }

    public TPlus getPlus()
    {
        return _plus_;
    }

    public void setPlus(TPlus node)
    {
        if(_plus_ != null)
        {
            _plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _plus_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_plus_);
    }

    void removeChild(Node child)
    {
        if(_plus_ == child)
        {
            _plus_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

    }
}
