/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class TMcFunction extends Token
{
    public TMcFunction()
    {
        super.setText("function");
    }

    public TMcFunction(int line, int pos)
    {
        super.setText("function");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMcFunction(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMcFunction(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMcFunction text.");
    }
}
