/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class TMcPrint extends Token
{
    public TMcPrint()
    {
        super.setText("print");
    }

    public TMcPrint(int line, int pos)
    {
        super.setText("print");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMcPrint(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMcPrint(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMcPrint text.");
    }
}
