/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class TMcTo extends Token
{
    public TMcTo()
    {
        super.setText("to");
    }

    public TMcTo(int line, int pos)
    {
        super.setText("to");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMcTo(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMcTo(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMcTo text.");
    }
}
