/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class TMcVar extends Token
{
    public TMcVar()
    {
        super.setText("var");
    }

    public TMcVar(int line, int pos)
    {
        super.setText("var");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMcVar(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMcVar(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMcVar text.");
    }
}
