/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class X1PCallParams extends XPCallParams
{
    private XPCallParams _xPCallParams_;
    private PCallParams _pCallParams_;

    public X1PCallParams()
    {
    }

    public X1PCallParams(
        XPCallParams _xPCallParams_,
        PCallParams _pCallParams_)
    {
        setXPCallParams(_xPCallParams_);
        setPCallParams(_pCallParams_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPCallParams getXPCallParams()
    {
        return _xPCallParams_;
    }

    public void setXPCallParams(XPCallParams node)
    {
        if(_xPCallParams_ != null)
        {
            _xPCallParams_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPCallParams_ = node;
    }

    public PCallParams getPCallParams()
    {
        return _pCallParams_;
    }

    public void setPCallParams(PCallParams node)
    {
        if(_pCallParams_ != null)
        {
            _pCallParams_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pCallParams_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPCallParams_ == child)
        {
            _xPCallParams_ = null;
        }

        if(_pCallParams_ == child)
        {
            _pCallParams_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPCallParams_) +
            toString(_pCallParams_);
    }
}
