/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class X2PCallParams extends XPCallParams
{
    private PCallParams _pCallParams_;

    public X2PCallParams()
    {
    }

    public X2PCallParams(
        PCallParams _pCallParams_)
    {
        setPCallParams(_pCallParams_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PCallParams getPCallParams()
    {
        return _pCallParams_;
    }

    public void setPCallParams(PCallParams node)
    {
        if(_pCallParams_ != null)
        {
            _pCallParams_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pCallParams_ = node;
    }

    void removeChild(Node child)
    {
        if(_pCallParams_ == child)
        {
            _pCallParams_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pCallParams_);
    }
}
