/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.languageparser.node;

import fr.umlv.ir2.compil.languageparser.analysis.*;

public final class X2PParams extends XPParams
{
    private PParams _pParams_;

    public X2PParams()
    {
    }

    public X2PParams(
        PParams _pParams_)
    {
        setPParams(_pParams_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PParams getPParams()
    {
        return _pParams_;
    }

    public void setPParams(PParams node)
    {
        if(_pParams_ != null)
        {
            _pParams_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pParams_ = node;
    }

    void removeChild(Node child)
    {
        if(_pParams_ == child)
        {
            _pParams_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pParams_);
    }
}
