/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.cmdlineparser.node;

import java.util.*;
import fr.umlv.ir2.compil.cmdlineparser.analysis.*;

public final class AEmptyOptionsStart extends POptionsStart
{

    public AEmptyOptionsStart()
    {
    }
    public Object clone()
    {
        return new AEmptyOptionsStart();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyOptionsStart(this);
    }

    public String toString()
    {
        return "";
    }

    void removeChild(Node child)
    {
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }
}
