/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.cmdlineparser.node;

import java.util.*;
import fr.umlv.ir2.compil.cmdlineparser.analysis.*;

public final class ALexOptionsEnd extends POptionsEnd
{
    private TOptLex _optLex_;
    private TQuote _right_;
    private POptionsStart _optionsStart_;

    public ALexOptionsEnd()
    {
    }

    public ALexOptionsEnd(
        TOptLex _optLex_,
        TQuote _right_,
        POptionsStart _optionsStart_)
    {
        setOptLex(_optLex_);

        setRight(_right_);

        setOptionsStart(_optionsStart_);

    }
    public Object clone()
    {
        return new ALexOptionsEnd(
            (TOptLex) cloneNode(_optLex_),
            (TQuote) cloneNode(_right_),
            (POptionsStart) cloneNode(_optionsStart_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALexOptionsEnd(this);
    }

    public TOptLex getOptLex()
    {
        return _optLex_;
    }

    public void setOptLex(TOptLex node)
    {
        if(_optLex_ != null)
        {
            _optLex_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _optLex_ = node;
    }

    public TQuote getRight()
    {
        return _right_;
    }

    public void setRight(TQuote node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public POptionsStart getOptionsStart()
    {
        return _optionsStart_;
    }

    public void setOptionsStart(POptionsStart node)
    {
        if(_optionsStart_ != null)
        {
            _optionsStart_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _optionsStart_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_optLex_)
            + toString(_right_)
            + toString(_optionsStart_);
    }

    void removeChild(Node child)
    {
        if(_optLex_ == child)
        {
            _optLex_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

        if(_optionsStart_ == child)
        {
            _optionsStart_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_optLex_ == oldChild)
        {
            setOptLex((TOptLex) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((TQuote) newChild);
            return;
        }

        if(_optionsStart_ == oldChild)
        {
            setOptionsStart((POptionsStart) newChild);
            return;
        }

    }
}
