/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.ir2.compil.cmdlineparser.node;

import fr.umlv.ir2.compil.cmdlineparser.analysis.*;

public final class X2POptionsStart extends XPOptionsStart
{
    private POptionsStart _pOptionsStart_;

    public X2POptionsStart()
    {
    }

    public X2POptionsStart(
        POptionsStart _pOptionsStart_)
    {
        setPOptionsStart(_pOptionsStart_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public POptionsStart getPOptionsStart()
    {
        return _pOptionsStart_;
    }

    public void setPOptionsStart(POptionsStart node)
    {
        if(_pOptionsStart_ != null)
        {
            _pOptionsStart_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pOptionsStart_ = node;
    }

    void removeChild(Node child)
    {
        if(_pOptionsStart_ == child)
        {
            _pOptionsStart_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pOptionsStart_);
    }
}
